apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: ammarabdelhady8132/vprofileapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "vprodb"
        - name: CACHE_HOST
          value: "vprocache01"
        - name: MQ_HOST
          value: "vpromq01"
---
apiVersion: v1
kind: Service
metadata:
  name: vproapp
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: vproapp
  type: ClusterIP
